In [1]:
import numpy as np
import cv2
import math
import matplotlib.pyplot as plt

In [2]:
def correlation2d(input_image, kernel, stride= np.array([[1], [1]]),  padding= np.array([[0], [0]])):
    
    stride_x = stride[1,0]
    stride_y = stride[0,0]
    padding_x = padding[1,0]
    padding_y = padding[0,0]
    
    def corr(img, ker, stri_x, stri_y):
        h, w = ker.shape
        r,c = img.shape
        out = np.zeros((math.floor(((r - h )/ stri_x)+ 1), math.floor(((c - w )/ stri_y)+ 1)))
        for i in range(out.shape[0]):
            for j in range(out.shape[1]):
                out[i, j] = (img[i* stri_x: i* stri_x+ h, j* stri_y : j* stri_y + w] * ker).sum()
        # out = (out)/255       # normalize to rescale intensity 0-255
        return out           # returns correlation for 2D image and kernel with given stride
    
    if input_image.ndim == 2:
        # apply equal padding on both sides(left/right, up/down) 
        if padding_x != 0 or padding_y != 0:
            image_padded = np.zeros((input_image.shape[0] + padding_x*2, input_image.shape[1] + padding_y*2))
            image_padded[padding_x:-1 *padding_x, padding_y:-1*padding_y] = input_image
        else:
            image_padded = input_image
        output = corr(image_padded, kernel,stride_x, stride_y)
        
    if input_image.ndim == 3:
        # apply equal padding on both sides(left/right, up/down) for 3 channels
        if padding_x != 0 or padding_y != 0:
            image_padded = np.zeros((input_image.shape[0] + padding_x*2, input_image.shape[1] + padding_y*2, 3))
            image_padded[padding_x:-1 * padding_x, padding_y:-1*padding_y,:] = input_image
        else:
            image_padded = input_image
        output = np.zeros((math.floor(((image_padded.shape[0] - kernel.shape[0])/stride_x)+ 1), 
                           math.floor(((image_padded.shape[1] - kernel.shape[1] )/stride_y)+ 1),3))
        for i in range(3):
             # stacking correlation op in N*M*3 array
            output[:,:,i] = corr(image_padded[:,:,i], kernel, stride_x, stride_y)
                   
    return output

In [41]:
X = cv2.imread("Lena.png")
#image = cv2.cvtColor(X, cv2.COLOR_BGR2GRAY)
#i = np.array([[1,2,3,4],[1,5,0,1],[1,0,0,1],[2,1,2,1]])

#K= np.array([[1,0,-1],[0,0,0],[-1,0,1]])
#K= np.array([[0,-1,0],[-1,4,-1],[0,-1,0]])
#K =  np.array([[-1, -1, -1], [-1, 8, -1], [-1, -1, -1]])

#K= np.array([[0,-1,0],[-1,5,-1],[0,-1,0]])

K= np.array([[1,1,1],[1,1,1],[1,1,1]])/9
#K = np.array([[1,2,1], [2,4,2], [1,2,1]])/16
#K = np.array([[1,4,6,4,1],[4,16,24,16,4],[6,24,36,24,6],[4,16,24,16,4],[1,4,6,4,1]])/256
#print(K.shape)
#print(image.shape)
stri= np.array([[2], [3]])
pad= np.array([[1], [1]])
#print(pad.shape)
#out = correlation2d(X, K)
output = convolution2d(X, K)
cv2.imwrite("Blur_1.jpg", output)

#cv2.imshow("Input_image", X)
#cv2.imshow("Correlation", out)
#cv2.imshow("convolution",output)
#cv2.waitKey(0)
#cv2.destroyAllWindows()

True

In [29]:
def convolution2d(input_image, kernel, stride= np.array([[1], [1]]),  padding= np.array([[0], [0]])):
    #kernel = np.flipud(np.fliplr(kernel))
    kernel = kernel[::-1, ::-1]
    stride_x = stride[1,0]
    stride_y = stride[0,0]
    padding_x = padding[1,0]
    padding_y = padding[0,0]
    
    def conv(img, ker, stri_x, stri_y):
        h, w = ker.shape
        r,c = img.shape
        out = np.zeros((math.floor(((r - h )/ stri_x)+ 1), math.floor(((c - w )/ stri_y)+ 1)))
        for i in range(out.shape[0]):
            for j in range(out.shape[1]):
                out[i, j] = (img[i* stri_x: i* stri_x+ h, j* stri_y : j* stri_y + w] * ker).sum()
        #out = (out)/255       # normalize to rescale intensity 0-255
        return out           # returns convolution for 2D image and kernel with given stride
    
    if input_image.ndim == 2:
        # apply equal padding on both sides(left/right, up/down) 
        if padding_x != 0 or padding_y != 0:
            image_padded = np.zeros((input_image.shape[0] + padding_x*2, input_image.shape[1] + padding_y*2))
            image_padded[padding_x:-1*padding_x, padding_y:-1*padding_y] = input_image
        else:
            image_padded = input_image
        output = conv(image_padded, kernel,stride_x, stride_y)
        
    if input_image.ndim == 3:
        # apply equal padding on both sides(left/right, up/down) for 3 channels
        if padding_x != 0 or padding_y != 0:
            image_padded = np.zeros((input_image.shape[0] + padding_x*2, input_image.shape[1] + padding_y*2, 3))
            image_padded[padding_x:-1 * padding_x, padding_y:-1*padding_y,:] = input_image
        else:
            image_padded = input_image
        output = np.zeros((math.floor(((image_padded.shape[0] - kernel.shape[0])/stride_x)+ 1), 
                           math.floor(((image_padded.shape[1] - kernel.shape[1] )/stride_y)+ 1),3))
        for i in range(3):
             # stacking convolve op in N*M*3 array
            output[:,:,i] = conv(image_padded[:,:,i], kernel, stride_x, stride_y)
                   
    return output


In [16]:
print(out)

[[[ 1.47058824  1.61176471  2.65882353]
  [ 1.09411765  1.07843137  1.7372549 ]
  [ 0.9254902   1.1254902   1.78431373]
  ...
  [ 1.01568627  1.1372549   1.80784314]
  [ 0.95686275  1.18039216  1.8627451 ]
  [ 0.89411765  1.07058824  1.78039216]]

 [[ 0.98039216  1.0745098   1.77254902]
  [ 0.57254902  0.54117647  0.8627451 ]
  [ 0.45490196  0.58431373  0.89803922]
  ...
  [ 0.50980392  0.57254902  0.90980392]
  [ 0.4745098   0.59607843  0.94509804]
  [ 0.4627451   0.56078431  0.91372549]]

 [[ 0.90980392  1.03137255  1.81176471]
  [ 0.49803922  0.69803922  0.8627451 ]
  [ 0.61960784  0.52156863  0.85882353]
  ...
  [ 0.37647059  0.43529412  0.80392157]
  [ 0.11764706  0.11764706  0.57647059]
  [ 0.22352941 -0.03529412  0.30196078]]

 ...

 [[ 0.5254902   0.2         0.68627451]
  [ 0.25098039  0.13333333  0.39215686]
  [ 0.20392157  0.17647059  0.29411765]
  ...
  [ 0.24705882  0.16470588  0.37254902]
  [ 0.15686275  0.19215686  0.43529412]
  [ 0.26666667  0.09019608  0.58431373]]

 [